In [1]:
# Imports
import tweepy
import pandas as pd
import time

In [4]:
# !pip install tweepy

In [5]:
import os
os.getcwd()

'C:\\SMU\\Y3S2\\FYP\\Codes'

In [6]:
consumer_key = ""
consumer_secret = ""
access_token = ""
access_token_secret = ""

auth = tweepy.OAuthHandler(consumer_key, consumer_secret)
auth.set_access_token(access_token, access_token_secret)
api = tweepy.API(auth,wait_on_rate_limit=True)

In [3]:
!pip install snscrape

Collecting snscrape
  Downloading snscrape-0.3.4-py3-none-any.whl (35 kB)
Requirement already satisfied: lxml in c:\softwares\anaconda\envs\fyp\lib\site-packages (from snscrape) (4.6.1)
Requirement already satisfied: requests[socks] in c:\softwares\anaconda\envs\fyp\lib\site-packages (from snscrape) (2.24.0)
Requirement already satisfied: beautifulsoup4 in c:\softwares\anaconda\envs\fyp\lib\site-packages (from snscrape) (4.9.3)
Requirement already satisfied: idna<3,>=2.5 in c:\softwares\anaconda\envs\fyp\lib\site-packages (from requests[socks]->snscrape) (2.10)
Requirement already satisfied: certifi>=2017.4.17 in c:\softwares\anaconda\envs\fyp\lib\site-packages (from requests[socks]->snscrape) (2020.6.20)
Requirement already satisfied: chardet<4,>=3.0.2 in c:\softwares\anaconda\envs\fyp\lib\site-packages (from requests[socks]->snscrape) (3.0.4)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\softwares\anaconda\envs\fyp\lib\site-packages (from requests[socks]->snscrape) (1.25.11)
Requirement already satisfied: PySocks!=1.5.7,>=1.5.6; extra == "socks" in c:\softwares\anaconda\envs\fyp\lib\site-packages (from requests[socks]->snscrape) (1.7.1)
Requirement already satisfied: soupsieve>1.2; python_version >= "3.0" in c:\softwares\anaconda\envs\fyp\lib\site-packages (from beautifulsoup4->snscrape) (2.0.1)
Installing collected packages: snscrape
Successfully installed snscrape-0.3.4

ComfortDelgro

In [43]:
import snscrape.modules.twitter as sntwitter
import pandas

# Creating list to append tweet data to
tweets_list2 = []

# Using TwitterSearchScraper to scrape data and append tweets to list
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('comfortdelgro since:2021-01-18 until:2021-04-18').get_items()):
    if i>800:
        break
    tweets_list2.append([tweet.date, tweet.id, tweet.content, tweet.username])
    
# Creating a dataframe from the tweets list above
comfortdelgro_df = pd.DataFrame(tweets_list2, columns=['Datetime', 'Tweet Id', 'Text', 'Username'])

In [44]:
comfortdelgro_df

,Datetime,Tweet Id,Text,Username
0,2021-04-16 10:20:16+00:00,1383002294065659907,https://t.co/nC7u34wzPb\nComfortDelGro stock h...,prosperusasia
1,2021-04-16 09:13:04+00:00,1382985384657776646,DBS reveals 7 stock picks – including ComfortD...,readtheedge_sg
2,2021-04-16 07:42:37+00:00,1382962621872287745,I'm at ComfortDelGro Engineering https://t.co/...,lexelledextjluv
3,2021-04-12 23:48:56+00:00,1381756249444913153,You Can Now Ebook A ComfortDelGro Cab On Lazad...,YourLife2Enjoy
4,2021-04-12 23:40:36+00:00,1381754152766873603,You Can Now Book A ComfortDelGro Cab On Lazada...,LinezNews
...,...,...,...,...
180,2021-01-28 10:56:06+00:00,1354745056943435779,ComfortDelGro to trial ride-hailing service wi...,TODAYonline
181,2021-01-28 10:50:04+00:00,1354743540824203264,ComfortDelGro to trial ride-hailing service wi...,TODAYonline
182,2021-01-28 10:00:02+00:00,1354730947216699392,ComfortDelGro trials new ride-hailing service ...,readtheedge_sg
183,2021-01-18 12:40:03+00:00,1351147338669166593,ComfortDelgro: Why my thesis does not hold tru...,TheFinance_sg
184,2021-01-18 11:19:09+00:00,1351126981040025604,I’m trying to write more short articles lately...,financeandtoast

In [45]:
import numpy as np
np.unique(comfortdelgro_df['Username'])

array(['AINewsFeed', 'AndyVermaut', 'AsiaWindEnergy', 'BCCletts',
       'BenPaulBT', 'BrokersTiger', 'BusinessTimes', 'CampaignAsia',
       'ChannelNewsAsia', 'Chemist_Sim', 'Ciaosssuuu', 'ConsultancyAsia',
       'DianaAurora96', 'DisruptiveAsean', 'FlaShBloGLive',
       'FooooooMedia', 'FutureTravelCo', 'GuardianNews24', 'HAREN__24',
       'HAccordingly', 'HIREMAIDEA', 'IndependentSG', 'IntrepideCoeur',
       'LTDAtaxinews', 'LinezNews', 'MSN_Singapore', 'Mano_RBLXI1',
       'MarketingEds', 'MartaFrazier', 'NikkeiAsia', 'OLMarketing_b',
       'PREcho_de', 'PanamericanaSRL', 'RATPGroup_Terr', 'ResearchPool',
       'SLNClicks', 'ShridharSachin', 'THEBMGLOBALNEWS', 'TINMobileNews',
       'TODAYonline', 'TheDrum', 'TheFinance_sg', 'Transport_AA',
       'TrendzNewsbd', 'VickyMogan', 'VimoServices', 'WMBtweets',
       'WaYs2rOcK', 'YSinSingapore', 'YourLife2Enjoy', 'aimer_riska',
       'albitrossnews', 'anith', 'bamaxiyu', 'bentruscello', 'cbasia',
       'centpercent', 'chokfern', 'comadad', 'dcJeyapaul', 'drivenowmag',
       'dtboyd', 'ecobusinesscom', 'ediz1975', 'edwinksl', 'ereik',
       'ericdss', 'eugenenitic', 'financeandtoast', 'financegnome',
       'gillianparker3', 'hoteldealphuket', 'into_AI', 'investoriamsg',
       'italiasingapore', 'legoboku', 'lexelledextjluv', 'milocamj',
       'my_tradingview', 'news_bht', 'nurjeevangsr', 'piduruviswa',
       'presse_mobi', 'presseticker', 'prosperusasia', 'ptiongson',
       'rajsgpre', 'readtheedge_sg', 'schlaunews', 'scott_mcmaster',
       'sehof', 'shflazhr', 'stompsingapore', 'straits_times',
       'stuarticus', 'tcku', 'techenttv', 'techinasia', 'tennouj',
       'therealdojj', 'theshowbus', 'tobiaskintzel', 'vt_chethan',
       'wheeeitsme', 'williswee', 'yclian', 'yogiliman', 'yperic'],
      dtype=object)

In [46]:
user_list = ['BusinessTimes','ChannelNewsAsia','TODAYonline','IndependentSG', 'techinasia', 'LinezNews', 'readtheedge_sg', 'MSN_Singapore']
comfortdelgro_df = comfortdelgro_df[~comfortdelgro_df['Username'].isin(user_list)]

In [47]:
comfortdelgro_df

,Datetime,Tweet Id,Text,Username
0,2021-04-16 10:20:16+00:00,1383002294065659907,https://t.co/nC7u34wzPb\nComfortDelGro stock h...,prosperusasia
2,2021-04-16 07:42:37+00:00,1382962621872287745,I'm at ComfortDelGro Engineering https://t.co/...,lexelledextjluv
3,2021-04-12 23:48:56+00:00,1381756249444913153,You Can Now Ebook A ComfortDelGro Cab On Lazad...,YourLife2Enjoy
5,2021-04-12 23:33:08+00:00,1381752274003763202,"When are we going to go offline if our, server...",Mano_RBLXI1
7,2021-04-12 11:27:39+00:00,1381569698962153477,@mmm268mmm バス乗り場行くのメンドウだからGrab\nComfortDelGro入...,YSinSingapore
...,...,...,...,...
177,2021-01-28 13:24:31+00:00,1354782406948003844,"""The move, which will serve to supplement Comf...",legoboku
178,2021-01-28 13:05:02+00:00,1354777507078098944,ComfortDelgro Taxi to start month-long trial o...,straits_times
179,2021-01-28 11:56:29+00:00,1354760255536816131,Interesting that the country’s dominant taxi i...,ericdss
183,2021-01-18 12:40:03+00:00,1351147338669166593,ComfortDelgro: Why my thesis does not hold tru...,TheFinance_sg
184,2021-01-18 11:19:09+00:00,1351126981040025604,I’m trying to write more short articles lately...,financeandtoast

In [48]:
comfortdelgro_df['Username'].unique()

array(['prosperusasia', 'lexelledextjluv', 'YourLife2Enjoy',
       'Mano_RBLXI1', 'YSinSingapore', 'GuardianNews24', 'yclian',
       'tennouj', 'stompsingapore', 'ereik', 'VimoServices',
       'italiasingapore', 'HAREN__24', 'financegnome', 'SLNClicks',
       'AsiaWindEnergy', 'FlaShBloGLive', 'edwinksl', 'TINMobileNews',
       'AndyVermaut', 'HAccordingly', 'schlaunews', 'presse_mobi',
       'presseticker', 'PREcho_de', 'ShridharSachin', 'HIREMAIDEA',
       'piduruviswa', 'IntrepideCoeur', 'comadad', 'DisruptiveAsean',
       'scott_mcmaster', 'ptiongson', 'tobiaskintzel', 'WaYs2rOcK',
       'centpercent', 'AINewsFeed', 'into_AI', 'OLMarketing_b',
       'milocamj', 'nurjeevangsr', 'techenttv', 'TheDrum',
       'hoteldealphuket', 'anith', 'williswee', 'yogiliman', 'chokfern',
       'gillianparker3', 'ecobusinesscom', 'bamaxiyu', 'TrendzNewsbd',
       'THEBMGLOBALNEWS', 'ConsultancyAsia', 'vt_chethan', 'Chemist_Sim',
       'bentruscello', 'ResearchPool', 'dtboyd', 'cbasia', 'news_bht',
       'CampaignAsia', 'FutureTravelCo', 'WMBtweets', 'PanamericanaSRL',
       'MarketingEds', 'dcJeyapaul', 'rajsgpre', 'theshowbus',
       'wheeeitsme', 'shflazhr', 'MartaFrazier', 'stuarticus',
       'TheFinance_sg', 'BenPaulBT', 'VickyMogan', 'tcku', 'Ciaosssuuu',
       'my_tradingview', 'BCCletts', 'therealdojj', 'ediz1975',
       'RATPGroup_Terr', 'BrokersTiger', 'aimer_riska', 'DianaAurora96',
       'sehof', 'NikkeiAsia', 'investoriamsg', 'albitrossnews',
       'eugenenitic', 'FooooooMedia', 'Transport_AA', 'drivenowmag',
       'LTDAtaxinews', 'yperic', 'legoboku', 'straits_times', 'ericdss',
       'financeandtoast'], dtype=object)

In [49]:
comfortdelgro_df.to_csv(path_or_buf = 'C:/SMU/Y3S2/FYP/NEW_DATA/comfort_delgro.csv', index = False)

Grab

In [74]:
# Creating list to append tweet data to
tweets_list3 = []

# Using TwitterSearchScraper to scrape data and append tweets to list
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('grabsg since:2018-01-18 until:2020-01-18').get_items()):
    if i>800:
        break
    tweets_list3.append([tweet.date, tweet.id, tweet.content, tweet.user.username, tweet.user.followersCount])
    
# Creating a dataframe from the tweets list above
grab_df = pd.DataFrame(tweets_list3, columns=['Datetime', 'Tweet Id', 'Text', 'Username', 'Followers'])

In [75]:
grab_df

,Datetime,Tweet Id,Text,Username,Followers
0,2020-01-17 18:30:00+00:00,1218239060180963328,Thousands of tuk-tuk drivers in Cambodia are t...,TRF_Stories,80291
1,2020-01-17 16:09:36+00:00,1218203726722338819,The top ridesharing and taxi app worldwide for...,SensorTower,17296
2,2020-01-17 14:08:47+00:00,1218173321662976002,@GrabSG Why? You’ve already said you won’t com...,tmittra,329
3,2020-01-17 14:03:05+00:00,1218171890549673984,"@tmittra Oh no, so sorry to hear this Tanuka. ...",GrabSG,22320
4,2020-01-17 13:57:58+00:00,1218170601656872960,@GrabSG It’s not feeling this way. Your own ca...,tmittra,329
...,...,...,...,...,...
796,2019-12-23 02:18:10+00:00,1208934792152018944,Top #ewallet apps in Singapore https://t.co/EE...,kunalpatel085,2724
797,2019-12-23 01:39:49+00:00,1208925144971759616,@vikijr_10 Sorry! Our Grab Car fares are dynam...,GrabSG,22320
798,2019-12-23 01:36:44+00:00,1208924368794861569,@nadh24 Awwh that's so sweet! True friends are...,GrabSG,22320
799,2019-12-23 01:32:38+00:00,1208923336748593152,@Aisyahxo That's dangerous! Please DM us more ...,GrabSG,22320
800,2019-12-23 01:31:27+00:00,1208923039489937409,"@ameraaene There there Amira, here's hoping th...",GrabSG,22320

In [79]:
grab_df = grab_df[grab_df['Followers'] < 100]

In [80]:
grab_df.to_csv(path_or_buf = 'D:/Y3S2/FYP/grab_tweets.csv', index = False)

MRT

In [51]:
# Creating list to append tweet data to
tweets_list4 = []

# Using TwitterSearchScraper to scrape data and append tweets to list
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('smrtsg since:2021-01-18 until:2021-04-18').get_items()):
    if i>800:
        break
    tweets_list4.append([tweet.date, tweet.id, tweet.content, tweet.username])
    
# Creating a dataframe from the tweets list above
smrt_df = pd.DataFrame(tweets_list4, columns=['Datetime', 'Tweet Id', 'Text', 'Username'])

In [52]:
smrt_df

,Datetime,Tweet Id,Text,Username
0,2021-04-13 09:50:57+00:00,1381907751882747907,@mrbrown @smrtsg,leongfifteen
1,2021-04-10 04:39:41+00:00,1380742257838419969,It is unfortunate that the British Monarchy di...,smrtsg
2,2021-04-04 14:51:47+00:00,1378721968677998593,@smrtsg https://t.co/Bz2WsH0URB,zecchilovek
3,2021-03-29 12:45:00+00:00,1376515736403800072,This is called a COVID clusterfuck. Don’t bree...,smrtsg
4,2021-03-29 05:19:12+00:00,1376403547365863424,Fuckin' A!\n\nhttps://t.co/E4UCQBbf6O,smrtsg
...,...,...,...,...
216,2021-01-26 00:38:32+00:00,1353864867501862912,@smrtsg @mediumshawn Oof!,tambahsambal
217,2021-01-26 00:00:16+00:00,1353855238155849729,@smrtsg @mediumshawn There are always folks wh...,BuilderBob1313
218,2021-01-25 16:30:57+00:00,1353742161360125958,@smrtsg @mediumshawn yo someones back 😳,beaunitebaez
219,2021-01-25 16:29:51+00:00,1353741885538496512,It’s ok to be a mediocre journalist @mediumsha...,smrtsg
220,2021-01-25 15:55:22+00:00,1353733205694808065,@food_blogger @mediumshawn Lol what a dishones...,smrtsg

In [53]:
smrt_df['Username'].unique()

array(['leongfifteen', 'smrtsg', 'zecchilovek', 'SFazi001', 'Desmondxyz2',
       'DarthLauraLou', 'Jaggy_The_Red', 'sskee', 'Safuannnn',
       'ekming751', 'A432z', 'kianteo777', 'DamianJenn2605',
       'squiidiqahh', 'IpestM', 'BrianSiow2', 'lyrical_fish',
       'SuryaMataram', 'geek3388', 'SMW772', '2021_Not1988', 'lomovsky',
       'ybrippler', 'dhaya_diet', 'GFoppy', 'p3pp3rmintkid', 'FJ_Ind',
       'FianFazlie', 'jmgvostpt', 'shekynshakingit', 'the3AMshowsg',
       'Ziggysworld1', 'Violectric', 'YeoYeHang', 'AndrewOYK',
       'handsome_river', 'JJ_Angelus', 'tinyfif', 'omarshariff316',
       'fordlynxrs', 'yuenck3', 'blackadlerqueen', 'Memoir1966',
       'Don_TheRealOne', 'p3ngs1ng', 'crusaderace2000', 'Gg67263436',
       'BM_Pancake', 'ultrabisupreme', 'iwritecoolstuff', 'myleyantay',
       'BuatDemokrasi', 'Owlridethesky', 'eatpraylurk', 'Kw1q51lv3r',
       'Cosmic_Wyrm', 'beefhorfun', 'omyhangu', 'elvishgambino',
       'nashhyyy', 'barisanhantu', 'mingolbacon', 'happentobeshort',
       'RIPhoeste', 'prickofdeath', 'whiprash', 'tambahsambal',
       'BuilderBob1313', 'beaunitebaez'], dtype=object)

In [54]:
user_list = ['smrtsg']
smrt_df = smrt_df[~smrt_df['Username'].isin(user_list)]

In [55]:
smrt_df.to_csv(path_or_buf = 'C:/SMU/Y3S2/FYP/NEW_DATA/smrt.csv', index = False)

SBS Transit

In [63]:
# Creating list to append tweet data to
tweets_list7 = []

# Using TwitterSearchScraper to scrape data and append tweets to list
for i,tweet in enumerate(sntwitter.TwitterSearchScraper('SBS Transit since:2021-01-18 until:2021-04-18').get_items()):
    if i>1100:
        break
    tweets_list7.append([tweet.date, tweet.id, tweet.content, tweet.username])
    
# Creating a dataframe from the tweets list above
sbstransit_df = pd.DataFrame(tweets_list7, columns=['Datetime', 'Tweet Id', 'Text', 'Username'])

In [64]:
sbstransit_df

,Datetime,Tweet Id,Text,Username
0,2021-04-17 23:16:58+00:00,1383560144043200516,Auto Retweet SBSTransit_Ltd *AUTO SCRIPT AT Ap...,speedknight
1,2021-04-17 20:36:34+00:00,1383519780972359691,If any noobs🙄🙄🙄(/j) need tips it’s bc it’s SBS...,AbsolutLesbian
2,2021-04-17 12:33:42+00:00,1383398262363758601,@ferrycoin @ZBScapital \n@vvaayu \n@SBSTransit...,Stephen2_1626
3,2021-04-17 08:16:51+00:00,1383333624678805504,Auto Retweet SBSTransit_Ltd *AUTO SCRIPT AT Ap...,speedknight
4,2021-04-17 08:16:51+00:00,1383333621826691077,Auto Retweet SBSTransit_Ltd *AUTO SCRIPT AT Ap...,speedknight
...,...,...,...,...
424,2021-01-18 15:43:56+00:00,1351193614915948549,A year ago was a today only a Single Decker Me...,aloysiuslow92
425,2021-01-18 15:43:55+00:00,1351193612814606338,A year ago was a today bus MAN A95 EU6 onboard...,aloysiuslow92
426,2021-01-18 11:16:14+00:00,1351126245677924358,Auto Retweet SBSTransit_Ltd *AUTO SCRIPT AT Ja...,speedknight
427,2021-01-18 09:16:28+00:00,1351096105329692674,Auto Retweet SBSTransit_Ltd *AUTO SCRIPT AT Ja...,speedknight
428,2021-01-18 01:16:07+00:00,1350975223936536577,Auto Retweet SBSTransit_Ltd *AUTO SCRIPT AT Ja...,speedknight

In [111]:
sbstransit_df = sbstransit_df[sbstransit_df['Followers'] < 300]

In [112]:
sbstransit_df.to_csv(path_or_buf = 'D:/Y3S2/FYP/sbstransit_tweets.csv', index = False)

In [65]:
sbstransit_df['Username'].unique()

array(['speedknight', 'AbsolutLesbian', 'Stephen2_1626', 'whyPerera',
       'joshua57ng', 'catsmaykill', 'milkyskull', 'Ameya_Kamat', 'lws_sg',
       'YongsukHur', 'SangShiJie', 'LandTptGuru', 'gyuranghae',
       'AsianCenturyStx', 'nahid2020', 'asyrafi_amir', 'EngineersDay',
       'SuriyaSubraman', 'BfdiHeng', 'namlaSSalman', 'fuckingsian',
       'bedcarp', 'globalfirstnews', 'HeySayMarcus', 'lexelledextjluv',
       'Easy_Branches', 'lastminutesnews', 'ardyyyanugrah', 'justintanwc',
       'yperic', 'HIREMAIDEA', 'kixes', 'straits_times', 'Keilo2000',
       'ajithkanth009', 'megamandung', 'BusNicholas', 'ayamnotsyar',
       '_boyyohboyy_', 'nagaklp1986', 'olyfernando', 'Mikeipoh1',
       'redhead38245215', 'D929_5051F', 'Mikelim12732167', 'saiko_plays',
       'cheyenneluyoga', 'eugene_chua', 'LeeGerwyn', 'archited88',
       'IzzulAyid', 'jmes_s', 'lameer96', 'marsordenis',
       'theedgemalaysia', 'pingkind', 'NEDworks', 'ThinkNotInform',
       'pipraiser', 'AndyVermaut', 'ChannelNewsAsia', 'BusinessTimes',
       'readtheedge_sg', 'EasyWorldNews', 'josephh_L', 'nazirahK',
       'IndependentSG', 'King25722491', 'NEWSWORLD555', 'TODAYonline',
       'NewsAsia24', 'SmartForecasts', 'lovpiko', 'khidirss', 'fm3930',
       'ndrhumra', 'frdyusf', 'mwthght', 'MHHBMN_', 'ThalesAsia',
       'chaeunion', 'napacindysekiew', 'bucellati0927', 'pheobetan',
       'PeregrinPenguin', 'gabby22182782', 'financegnome', '_moonkind',
       'bethanoot', 'LiquidityNews', 'hanistar101', 'HkRoundel',
       'Ch1llySauce', 'Changkz2', 'sgsgme', 'promisedpauper',
       'LuqmanSani', 'MRavilaw', 'hqlosmn', 'JJPaoloSA', 'carnagecaesar',
       'Syhrezd', 'Ahmad69138914', 'Jake64734467', 'Chemist_Sim',
       'MothershipSG', 'theironicstory', 'heytherelailaa',
       'SkinnyOpinions', 'hafanzeee', 'kevabra', 'SLNClicks', 'dnanerina',
       'RATPGroup_Terr', '_Jashan_Arora', 'abhi_mich22', 'MaminMarvel',
       'celineCLOUDSelf', 'monsieurgordon', 'basilyeo', 'ReinAlps',
       'raupunzelxxx', 'G_Luffyy', 'ShahiraZainal', 'bzlbsyr',
       'clubjeweI', 'shahfaridzhan', '_ashish_thapar_', 'qayyumsunawan',
       'madihahsaleh', '_vmsyvr_', 'saraven007', 'Mykarocknrollin',
       'BioGeni3', 'wearecryptoarmy', 'eu7in', 'gwangpee',
       'GlobalBusNews', 'railpage', 'isthislrnz', 'afiqron_',
       'Madhurendra_709', 'jsweng', 'basicbitche99', 'stompsingapore',
       'aloysiuslow92'], dtype=object)

In [66]:
user_list = ['ChannelNewsAsia', 'BusinessTimes',
       'readtheedge_sg', 'EasyWorldNews', 'IndependentSG', 'TODAYonline','NewsAsia24', 'MothershipSG', 'stompsingapore']
sbstransit_df = sbstransit_df[~sbstransit_df['Username'].isin(user_list)]

In [68]:
sbstransit_df.to_csv(path_or_buf = 'C:/SMU/Y3S2/FYP/NEW_DATA/sbstransit.csv', index = False)

In [69]:
frames = [comfortdelgro_df, smrt_df, sbstransit_df]

result = pd.concat(frames)

In [70]:
result

,Datetime,Tweet Id,Text,Username
0,2021-04-16 10:20:16+00:00,1383002294065659907,https://t.co/nC7u34wzPb\nComfortDelGro stock h...,prosperusasia
2,2021-04-16 07:42:37+00:00,1382962621872287745,I'm at ComfortDelGro Engineering https://t.co/...,lexelledextjluv
3,2021-04-12 23:48:56+00:00,1381756249444913153,You Can Now Ebook A ComfortDelGro Cab On Lazad...,YourLife2Enjoy
5,2021-04-12 23:33:08+00:00,1381752274003763202,"When are we going to go offline if our, server...",Mano_RBLXI1
7,2021-04-12 11:27:39+00:00,1381569698962153477,@mmm268mmm バス乗り場行くのメンドウだからGrab\nComfortDelGro入...,YSinSingapore
...,...,...,...,...
424,2021-01-18 15:43:56+00:00,1351193614915948549,A year ago was a today only a Single Decker Me...,aloysiuslow92
425,2021-01-18 15:43:55+00:00,1351193612814606338,A year ago was a today bus MAN A95 EU6 onboard...,aloysiuslow92
426,2021-01-18 11:16:14+00:00,1351126245677924358,Auto Retweet SBSTransit_Ltd *AUTO SCRIPT AT Ja...,speedknight
427,2021-01-18 09:16:28+00:00,1351096105329692674,Auto Retweet SBSTransit_Ltd *AUTO SCRIPT AT Ja...,speedknight
428,2021-01-18 01:16:07+00:00,1350975223936536577,Auto Retweet SBSTransit_Ltd *AUTO SCRIPT AT Ja...,speedknight

In [71]:
result.to_csv(path_or_buf = 'C:/SMU/Y3S2/FYP/NEW_DATA/new_twitter.csv', index = False)