In [522]:
import pandas as pd
from sklearn.metrics import accuracy_score

In [523]:
df = pd.read_csv('initial data as well as targeted output-RA-data-example -jiaxin-simple.csv')  #import reviews
df

,Sentiment,Sentiment Num,Multi,Text
0,Positive,1,1,"((3(4 you are all hail, good."
1,Negative,-1,-1,He is old age 4)4) @SBSTransit_Ltd.
2,Positive,1,1,haha fat farm!0)0 https://t.co/Nr8bEP93p0.
3,Negative,-1,-2,it is really that hard to get another PMET lev...
4,Negative,-1,-1,It could have saved his life ...
5,Positive,1,1,"I obtain award today, and feel like a million ..."
6,Negative,-1,-1,It's just plain sad.
7,Negative,-1,-1,Wonder how/what/who determines which ones get...
8,Negative,-1,-1,"""Force way"" coz Singaporean drivers don't give..."
9,Positive,1,1,Thank you uncle for the care delivery!
10,Positive,1,1,Thanks SMRT and SBS Transit! #smrt #sbstransit
11,Positive,1,2,(((0 (thank you. Thank you who offered to send...
12,Negative,-1,-1,In the morning $1.43 is deducted and in the ev...
13,Negative,-1,-1,@smrtsg Wow! Seriously? Picture might being E...
14,Negative,-1,-1,"@SBSTransit_Ltd fix your shit, almost 30 mins ..."
15,Negative,-1,-1,"it is late, almost 30 mins for a bus, what in ..."
16,Neutral,0,0,#CNY2020 from SBS Transit at NE4/DT19 Chinatow...

In [524]:
import re

def newtext(text):
    text = text.strip()
    text = text.replace('/\s\s+/g', ' ') # replace multiple spaces with a single space
    text = re.sub ('\s+', ' ', text)
    text = re.sub('@[^\s]+','',text)  # delete the username
    text = re.sub('&[^\s]+','',text)
    text = re.sub('#[^\s]+','',text)
    text = re.sub('".*?"', '', text)  # delete anything in quotation marks
    text = re.sub('http[s]?://\S+', '', text) # delete urls
    
    text = text.replace("extension service","extension-service") ## use replace words
    text = text.replace("extracurricular activity","extracurricular-activity")
    text = text.replace("alcohol addiction","alcohol-addiction")
    text = text.replace("bad condition","bad-condition")
    text = text.replace("health hazard","health-hazard")
    text = text.replace("old age","old-age")
    text = text.replace("persistent cruelty","persistent-cruelty")
    text = text.replace("poor shape","poor-shape")
    text = text.replace("sinking spell","sinking-spell")
    text = text.replace("Cut off","cut-off")
    text = text.replace("Cut away","cut-away")
    text = text.replace("Cut back","cut-back")
    text = text.replace("Fever has gone down","fever-gonedown")
    text = text.replace("take action","take-action")
    text = text.replace("advance directive","advance-directive")
    text = text.replace("all hail","all-hail")
    text = text.replace("care delivery","care-delivery")
    text = text.replace("electrolyte balance","electrolyte-balance")
    text = text.replace("fat farm","fat-farm")
    text = text.replace("feel like a million","feel-likeamillion")
    text = text.replace("feel like a million dollars","feel-likeamilliondollars")
    
    text = re.sub("\S*@\S*\s?",'',text)   # delete email address
    text = text.replace('\n', ' ').replace('\r', '')  # Clean up all "\n"

    text = re.sub(r'[\?\.\!]+(?=[\?\.\!])', '', text) ## replace mutiple ?, !, . with the last puntuation appeared 
    text = re.sub(r'[()@#&]', '', text)  #remove multiple non common puntuations
    
    numbers = '0123456789' ## add a space behind all puntuations except for the '.' decimal point 
    symbols = "?!,;:$" ## symbols to add in a black space behind 
    new_text = ''
    for index, char in enumerate(text):
      if char == ".": # check before and after
        try:
          if (not (text[index-1]) in numbers) or (not text[index+1] in numbers):
            new_text += ". "
          else:
            new_text += "."
        except IndexError:
          pass
      elif char in symbols:
        try:
          if text[index+1] != " ":
            if (text[index+1]) not in numbers:
              new_text += (char + " ")
            else:
              new_text += char
          else:
            new_text += char
        except IndexError:
          new_text += char
      else:
        new_text += char    
    text = new_text
    
    text= re.sub(' +', ' ', text)
    #text= re.sub(':', '', text)
    text= re.sub("[:']", '', text)
    #text = re.sub ('\s+', '', text)
    text = text.strip()
    return text.lower()

In [525]:
df["Text"] = df['Text'].apply(lambda text: newtext(text))

In [526]:
df.drop(df.columns[0], axis=1)

    Sentiment Num  Multi                                               Text
0               1      1                         34 you are all-hail, good.
1              -1     -1                                   he is old-age 44
2               1      1                                   haha fat-farm!00
3              -1     -2  it is really that hard to get another pmet lev...
4              -1     -1  it could have saved his life without the alcoh...
5               1      1  i obtain award today, and feel-likeamillion do...
6              -1     -1                                its just plain sad.
7              -1     -1  wonder how/what/who determines which ones get ...
8              -1     -1             coz singaporean drivers dont give way?
9               1      1             thank you uncle for the care-delivery!
10              1      1                       thanks smrt and sbs transit!
11              1      2  0 thank you. thank you who offered to send me ...
12             -1     -1  in the morning $1.43 is deducted and in the ev...
13             -1     -1        wow! seriously? picture might being edited?
14             -1     -1  fix your shit, almost 30 mins for a bus what i...
15             -1     -1  it is late, almost 30 mins for a bus, what in ...
16              0      0  from sbs transit at ne4/dt19 chinatown mrt int...

In [527]:
df.to_csv('output.csv')